// BasketApp.Core/Models/BasketItem.cs
using System.ComponentModel.DataAnnotations;

namespace ShoppingBasket.Core.Models
{
    public class BasketItem
    {
        public int Id { get; set; } // Primary key (auto-generated by the database)

        [Required] // Only ProductId and Quantity are required in the request
        public int ProductId { get; set; } // Foreign key to Product

        public Product? Product { get; set; } // Navigation property to Product (optional in request)

        [Required] // Quantity is required
        public int Quantity { get; set; } // Quantity of the product in the basket
        public int TransactionId { get; set; } // Foreign key to Transaction
        public Transaction Transaction { get; set; } // Navigation property to Transaction
    }
}